# Curated Wikimedia Commons candidates, a few per building, to inspect for
# people-free shots. Keys match records.json building ids.

CURATED = {
    "wumen": [
        "File:Meridian Gate (Forbidden City) 2015 August.jpg",
        "File:Meridian Gate (Forbidden City) 2010 April.jpg",
        "File:Meridian Gate (Forbidden City) 2015 December (morning).jpg",
        "File:Meridian Gate in snow (20220213153145).jpg",
        "File:Meridian Gate (Forbidden City) 2018-08-18 170110.jpg",
        "File:Meridian Gate, Forbidden City center.JPG",
        "File:Meridian Gate (Forbidden City) West wing interior 2015 December.jpg",
        "File:Meridian Gate (Forbidden City) East wing interior 2015 December.jpg",
        "File:Meridian gate in Beijing.jpg",
        "File:Wumen, Forbidden City, Beijing 2008.jpg",
        "File:Città proibita, porta meridiana (wumen) 01.jpg",
        "File:Città proibita, porta meridiana (wumen) 03.jpg",
        "File:故宫午门23.jpg",
        "File:午门俯瞰.jpg",
        "File:窗外的午门.jpg",
        "File:雪中紫禁城 02.jpg",
        "File:Forbidden City in snow.jpg",
    ],
    "taihemen": [
        "File:Gate of Supreme Harmony.JPG",
        "File:Gate of Supreme Harmony at the Forbidden City.jpg",
        "File:Gate of Supreme Harmony 20160826-1.jpg",
        "File:Back view of Gate of Supreme Harmony.jpg",
        "File:太和門 Gate of Supreme Harmony 2009-06-21.jpg",
    ],
    "taihedian": [
        "File:Hall of Supreme Harmony 2010.jpg",
        "File:Hall of Supreme Harmony.JPG",
        "File:Hall of Supreme Harmony (Forbidden City) 1.jpg",
        "File:Hall of Supreme Harmony 20160826-3.jpg",
        "File:The Hall of Supreme Harmony.jpg",
        "File:Hall of Supreme Harmony in snow (20220318153418).jpg",
        "File:Hall of Supreme Harmony in snow (20220318153516).jpg",
        "File:Hall of Supreme Harmony in snow (20220318153307).jpg",
        "File:Hall of Supreme Harmony cropped.jpg",
        "File:Hall of Supreme Harmony (Forbidden City) 2.jpg",
        "File:Hall of Supreme Harmony (Forbidden City) 3.jpg",
        "File:Hall of Supreme Harmony (20241127120000).jpg",
        "File:Peking verbotene stadt.jpg",
        "File:Hall of Supreme Harmony interior 2010 April.jpg",
        "File:太和殿內景.JPG",
        "File:Inside Great Hall.jpg",
        "File:太和殿皇帝寶座.JPG",
    ],
    "zhonghedian": [
        "File:Hall of Central Harmony.JPG",
        "File:Hall of Central Harmony 20160826.jpg",
        "File:20200110 Hall of Central Harmony-1.jpg",
        "File:Beijing Forbidden City Hall of Central Harmony terraces-20071018-RM-141732.jpg",
        "File:20200110 Hall of Central Harmony-2.jpg",
        "File:20200110 Hall of Central Harmony-3.jpg",
        "File:雪中紫禁城.jpg",
        "File:雪中紫禁城 01.jpg",
        "File:雪中紫禁城 1.jpg",
        "File:Inside view of Hall of Central Harmony 20160826.jpg",
    ],
    "baohedian": [
        "File:Hall of Preserving Harmony 20160826.jpg",
        "File:2015-01-10 Hall of Preserving Harmony (Forbidden City).jpg",
        "File:Hall of Preserving Harmony in snow (20220318160000).jpg",
        "File:Città proibita, padiglione dell'armonia perfetta (baohedian) 01.jpg",
        "File:·˙·ChinaUli2010·.· Beijing - Snow in the Forbidden Town - panoramio (23).jpg",
        "File:雪中紫禁城 5.jpg",
        "File:雪中紫禁城 6.jpg",
        "File:Inside view of Hall of Preserving Harmony 20160826.jpg",
        "File:Hall of Preserving Harmony interior 2010 April.jpg",
    ],
    "qianqinggong": [
        "File:Palace of Heavenly Purity 20160826.jpg",
        "File:Palace of Heavenly Purity (20220218132746).jpg",
        "File:QianQingGong.JPG",
        "File:View of Palace of Heavenly Purity.jpg",
        "File:Palace of Heavenly Purity (20220218132818).jpg",
        "File:Palace of Heavenly Purity 20160826-2.jpg",
        "File:Upper view of Palace of Heavenly Purity.jpg",
        "File:Inside view of Palace of Heavenly Purity 20160826.jpg",
        "File:乾清宮 Interior of Qianqing Palace - panoramio.jpg",
        "File:Dragon Throne Palace of Heavenly Purity Forbidden City Beijing.jpg",
    ],
    "jiaotaidian": [
        "File:Hall of Union and Peace 20160826.jpg",
        "File:Hall of Union and Peace 20160826-2.jpg",
        "File:交泰殿 Jiaotai Hall - panoramio.jpg",
        "File:Forbidden City IMG 4340 Hall of Celestial and Terrestrial Union (Jiaotaidian).jpg",
        "File:Forbidden City IMG 4342 Hall of Celestial and Terrestrial Union (Jiaotaidian).jpg",
        "File:Forbidden City IMG 4343 Hall of Celestial and Terrestrial Union (Jiaotaidian).jpg",
        "File:Forbidden City IMG 4345 Hall of Celestial and Terrestrial Union (Jiaotaidian).jpg",
    ],
    "kunninggong": [
        "File:Palace of Earthly Tranquility 20160826-1.jpg",
        "File:Palace of Earthly Tranquility (20220218133044).jpg",
        "File:Palace of Earthly Tranquility 20160826-2.jpg",
        "File:·˙·ChinaUli2010·.· Beijing - Snow in the Forbidden Town - panoramio (18).jpg",
        "File:·˙·ChinaUli2010·.· Beijing - Snow in the Forbidden Town - panoramio (19).jpg",
        "File:·˙·ChinaUli2010·.· Beijing - Snow in the Forbidden Town - panoramio (20).jpg",
        "File:坤寧宮喜床 The Wedding Bed in Kunning Palace - panoramio.jpg",
    ],
    "shenwumen": [
        "File:Gate of Divine Might 20160826.jpg",
        "File:Gate of Divine Might (Forbidden City) 2015 December.jpg",
        "File:Gate of Divine Might (Forbidden City) 2015 December (wide).jpg",
    ],
    "jiaolou": [
        "File:Corner Tower of the Forbidden City, Beijing.jpg",
        "File:North-eastern corner tower (Forbidden City) 2015 September.jpg",
        "File:North-western corner tower (Forbidden City) 2015 October.jpg",
        "File:Corner Tower of Forbidden City (20240627).jpg",
    ],
    "wenhuadian": [
        "File:文华殿.JPG",
        "File:20200110 Hall of Literary Glory gate-1.jpg",
        "File:Gate of Literary Glory 2015 December.jpg",
    ],
    "wuyingdian": [
        "File:Forbiddencityviewpic2.jpg",
        "File:Città proibita, padiglione dell'eminenza militare (wuyingmen) 01.jpg",
        "File:武英殿的出檐及走獸.JPG",
        "File:武英殿轉角鋪作.JPG",
    ],
    "wenyuange": [
        "File:Wenyuan Pavilion.png",
        "File:Wenyuan.jpg",
        "File:Wen Yuan Chamber.JPG",
    ],
    "yangxindian": [
        "File:Flickr - archer10 (Dennis) - China-6232.jpg",
        "File:Flickr - archer10 (Dennis) - China-6256.jpg",
        "File:Beijing 2006 2-58.jpg",
        "File:Forbidden City ovedc (17).JPG",
        "File:养心殿匾额.JPG",
        "File:吉祥门.JPG",
        "File:Beijing 2006 2-57.jpg",
    ],
    "jiulongbi": [
        "File:20090528 Beijing Nine Dragon Wall 7984.jpg",
        "File:Wall of Nine Dragons.jpg",
        "File:Beijing Forbidden city glazed-tile nine dragons screen(small)(2008-08).jpg",
    ],
    "xihuamen": [
        "File:West Glorious Gate (Forbidden City).jpg",
        "File:West Glorious Gate (20220213150635).jpg",
        "File:Forbidden City 20170801 101901.jpg",
        "File:West Glorious Gate (Forbidden City) 1.jpg",
        "File:West Glorious Gate (20220213150640).jpg",
        "File:West Glorious Gate (20220213150647).jpg",
    ],
    "cininggong": [
        "File:慈宁宫.JPG",
        "File:慈宁宫2.JPG",
        "File:The Forbidden City - Beijing 24 (4934789533).jpg",
        "File:故宫博物院 - panoramio (8).jpg",
    ],
    "chuxiugong": [
        "File:储秀宫.JPG",
        "File:Forbidden City August 2012 32.JPG",
    ],
    "qinandian": [
        "File:钦安殿.JPG",
        "File:钦安殿 - panoramio.jpg",
    ],
    "fengxiandian": [
        "File:奉先殿.jpg",
        "File:故宫博物院 - panoramio (8).jpg",
        "File:Forbidden City - panoramio (2).jpg",
        "File:故宮鐘錶館 Forbidden City Watch Museum - panoramio.jpg",
    ],
}
