"""Verify shiji_people.db against the cleaned 《史記》 originals.

Two jobs:
  1. Integrity: every non-empty source_quote (and every person origin_raw /
     heading_original) must appear verbatim in the processed chapter it cites.
  2. 20-row check: print N random rows beside the original sentence so a human
     can compare.  The report is written to research/outputs/verification.md.

Usage:
    python code/verify.py            # integrity + 20-row check
    python code/verify.py 30
"""
import json
import os
import random
import sqlite3
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:  # noqa: BLE001
    pass

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DB = os.path.join(ROOT, "shiji_people.db")
INDEX = os.path.join(ROOT, "sources", "raw", "sources_index.json")
PROC = os.path.join(ROOT, "sources", "processed")
REPORT = os.path.join(ROOT, "research", "outputs", "verification.md")

TABLES = ["persons", "person_chapters", "offices", "events", "relations"]


def main():
    n = int(sys.argv[1]) if len(sys.argv) > 1 else 20
    with open(INDEX, encoding="utf-8") as fh:
        index = json.load(fh)
    url_to_slug = {r["source_url"]: r["slug"] for r in index}

    conn = sqlite3.connect(DB)
    conn.row_factory = sqlite3.Row
    cache = {}

    def text_for(url):
        slug = url_to_slug.get(url)
        if not slug:
            return None
        if slug not in cache:
            with open(os.path.join(PROC, slug + ".txt"), encoding="utf-8") as fh:
                cache[slug] = fh.read()
        return cache[slug]

    checked = passed = failed = 0
    failures = []
    for table in TABLES:
        for row in conn.execute("SELECT * FROM %s" % table):
            url = row["source_url"] if "source_url" in row.keys() else None
            quote = (row["source_quote"] or "").strip()
            if quote:
                checked += 1
                src = text_for(url)
                if src is None:
                    failed += 1
                    failures.append((table, row["id"], "NO-SOURCE", quote))
                elif quote in src:
                    passed += 1
                else:
                    failed += 1
                    failures.append((table, row["id"], "QUOTE-NOT-FOUND", quote))
    for row in conn.execute("SELECT id,source_url,origin_raw,heading_original FROM persons"):
        for fld in ("origin_raw", "heading_original"):
            v = (row[fld] or "").strip()
            if not v:
                continue
            checked += 1
            src = text_for(row["source_url"])
            if src is not None and v in src:
                passed += 1
            else:
                failed += 1
                failures.append(("persons." + fld, row["id"], "NOT-FOUND", v))

    # ---- random N-row check ----
    pool = []
    for table in TABLES:
        for row in conn.execute("SELECT * FROM %s" % table):
            if (row["source_quote"] or "").strip():
                pool.append((table, dict(row)))
    pool.sort(key=lambda x: (x[0], x[1]["id"]))
    rng = random.Random(508)
    sample = rng.sample(pool, min(n, len(pool)))

    lines = []
    lines.append("# 20-row check — shiji_people.db\n")
    lines.append("Generated by `python code/verify.py`. Each row below is a random draw; "
                 "`original sentence` is the surrounding sentence from the cleaned "
                 "《史記》 chapter at `sources/processed/`.\n")
    lines.append("## Integrity\n")
    lines.append("- quoted facts checked: **%d**" % checked)
    lines.append("- matched verbatim: **%d**" % passed)
    lines.append("- mismatches: **%d**\n" % failed)
    if failures:
        lines.append("| table | id | kind | quote |")
        lines.append("|---|---|---|---|")
        for t, i, k, q in failures[:50]:
            lines.append("| %s | %s | %s | %s |" % (t, i, k, q[:60].replace("|", "\\|")))
        lines.append("")

    lines.append("## Random %d rows\n" % len(sample))
    for table, row in sample:
        src = text_for(row.get("source_url")) or ""
        quote = (row["source_quote"] or "").strip()
        ctx = ""
        p = src.find(quote)
        if p >= 0:
            seg = src[max(0, p - 40):p + len(quote) + 40].replace("\n", " ")
            ctx = "…" + seg + "…"
        lines.append("### [%s id=%s]" % (table, row["id"]))
        lines.append("- locator: `%s`" % (row.get("source_locator") or ""))
        lines.append("- DB value: %s" % (row.get("description") or row.get("title_chn")
                                         or row.get("related_name") or row.get("relation_kind")))
        lines.append("- source_quote: `%s`" % quote)
        lines.append("- in original: **%s**" % ("YES" if quote in src else "NO"))
        if ctx:
            lines.append("- context: %s" % ctx)
        lines.append("")

    with open(REPORT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))

    print("INTEGRITY: %d/%d quoted/derived fields matched their source" % (passed, checked))
    for t, i, k, q in failures[:30]:
        print("  FAIL %-20s %-16s id=%s  %s" % (t, k, i, q[:50]))
    print("random %d-row check written to %s" % (len(sample), REPORT))
    conn.close()
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
